# Generated by Django 3.1.3 on 2022-05-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acessorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('valor', models.FloatField()),
                ('quantidade', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='media')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mensages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('assunto', models.CharField(choices=[('comentario', 'Comentários'), ('critica', 'Críticas'), ('duvida', 'Dúvidas'), ('outro', 'Outros')], max_length=10)),
                ('mensagem', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('fabricante', models.CharField(max_length=255)),
                ('valor', models.FloatField()),
                ('motor', models.FloatField()),
                ('quantidade', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='media')),
                ('description', models.TextField()),
            ],
        ),
    ]
