# Generated by Django 3.1.3 on 2022-05-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferramentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('valor', models.FloatField()),
                ('quantidade', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='media')),
                ('description', models.TextField()),
            ],
        ),
    ]
